# Файл: render.yaml
# ОПИС: Виправлена версія з dockerContext для правильної збірки

services:
  # --- Backend: ASP.NET Core API ---
  - type: web
    name: thrume-api
    plan: free
    env: docker
    # Вказуємо Render перейти в цю папку перед збіркою
    dockerContext: ./src/backend/Thrume
    # Тепер шлях до Dockerfile відносний до dockerContext
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - src/backend/Thrume/**

  # --- Frontend: Vue.js + Nginx ---
  - type: web
    name: thrume-frontend
    plan: free
    env: docker
    # Вказуємо Render перейти в цю папку перед збіркою
    dockerContext: ./src/frontend/thrume-frontend
    # Тепер шлях до Dockerfile відносний до dockerContext
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - src/frontend/thrume-frontend/**