# Файл: render.yaml
# НОВИЙ ПІДХІД: Повністю відмовляємось від dockerContext і працюємо з кореня репозиторію.

services:
  # --- Backend: ASP.NET Core API ---
  - type: web
    name: thrume-api
    plan: free
    env: docker
    # НЕ ВИКОРИСТОВУЄМО dockerContext
    # Вказуємо повний шлях до Dockerfile від кореня репозиторію.
    dockerfilePath: ./src/backend/Thrume/Dockerfile
    buildFilter:
      paths:
        - src/backend/Thrume/**

  # --- Frontend: Vue.js + Nginx ---
  - type: web
    name: thrume-frontend
    plan: free
    env: docker
    # НЕ ВИКОРИСТОВУЄМО dockerContext
    # Вказуємо повний шлях до Dockerfile від кореня репозиторію.
    dockerfilePath: ./src/frontend/thrume-frontend/Dockerfile
    buildFilter:
      paths:
        - src/frontend/thrume-frontend/**