# Файл: render.yaml
# ВИПРАВЛЕНО: Спрощено dockerfilePath для відповідності до dockerContext

services:
  # --- Backend: ASP.NET Core API ---
  - type: web
    name: thrume-api
    plan: free
    env: docker
    # КОНТЕКСТ: Render переходить в цю папку.
    dockerContext: ./src/backend/Thrume
    # ШЛЯХ: Render шукає цей файл ВЖЕ ВСЕРЕДИНІ папки з dockerContext.
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - src/backend/Thrume/**

  # --- Frontend: Vue.js + Nginx ---
  - type: web
    name: thrume-frontend
    plan: free
    env: docker
    dockerContext: ./src/frontend/thrume-frontend
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - src/frontend/thrume-frontend/**