# Файл: render.yaml
# Опис інфраструктури для розгортання на Render

services:
  # --- Backend: ASP.NET Core API ---
  - type: web
    name: thrume-api # Це ім'я будемо використовувати в nginx.conf
    plan: free
    env: docker
    # Шлях до Dockerfile бекенду. Перевірте, чи він правильний!
    dockerfilePath: ./src/backend/Thrume/Dockerfile
    buildFilter:
      paths:
        - src/backend/Thrume/**

  # --- Frontend: Vue.js + Nginx ---
  - type: web # ЗМІНЕНО: тепер це web-сервіс, а не static
    name: thrume-frontend
    plan: free
    env: docker # Вказуємо, що розгортаємо за допомогою Docker
    # Шлях до Dockerfile фронтенду. Перевірте, чи він правильний!
    dockerfilePath: ./src/frontend/thrume-frontend/Dockerfile
    buildFilter:
      paths:
        - src/frontend/thrume-frontend/**